apiVersion: v2
name: gpu-operator
version: v23.9.1
kubeVersion: ">= 1.16.0-0"
description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
appVersion: "v23.9.1"
icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
sources:
- https://github.com/NVIDIA/gpu-operator
home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
keywords:
  - gpu
  - cuda
  - compute
  - operator
  - deep learning
  - monitoring
  - tesla

dependencies:
  - name: node-feature-discovery
    version: v0.14.2
    repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    condition: nfd.enabled
