apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-device-plugin-entrypoint
  namespace: "FILLED BY THE OPERATOR"
  labels:
    app: nvidia-device-plugin-daemonset
data:
  entrypoint.sh: |-
    #!/bin/bash

    driver_root=""
    driver_root_ctr_path=""
    while true; do
      if [[ -f /run/nvidia/validations/host-driver-ready ]]; then
        driver_root=/
        driver_root_ctr_path=/host
        break
      elif [[ -f /run/nvidia/validations/driver-ready ]]; then
        driver_root=/run/nvidia/driver
        driver_root_ctr_path=$driver_root
        break
      else
        echo "waiting for the driver validations to be ready..."
        sleep 5
      fi
    done

    export NVIDIA_DRIVER_ROOT=$driver_root
    echo "NVIDIA_DRIVER_ROOT=$NVIDIA_DRIVER_ROOT"

    export DRIVER_ROOT_CTR_PATH=$driver_root_ctr_path
    echo "DRIVER_ROOT_CTR_PATH=$DRIVER_ROOT_CTR_PATH"

    echo "Starting nvidia-device-plugin"
    exec nvidia-device-plugin
