apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-mig-manager-entrypoint
  namespace: "FILLED BY THE OPERATOR"
  labels:
    app: nvidia-mig-manager
data:
  entrypoint.sh: |-
    #!/bin/bash

    host_driver=""
    while true; do
      if [[ -f /run/nvidia/validations/host-driver-ready ]]; then
        host_driver=true
        break
      elif [[ -f /run/nvidia/validations/driver-ready ]]; then
        host_driver=false
        break
      else
        echo "waiting for the driver validations to be ready..."
        sleep 5
      fi
    done

    export WITH_SHUTDOWN_HOST_GPU_CLIENTS=$host_driver
    echo "WITH_SHUTDOWN_HOST_GPU_CLIENTS=$WITH_SHUTDOWN_HOST_GPU_CLIENTS"

    echo "Starting nvidia-mig-manager"
    exec nvidia-mig-manager
